### ISSUE TITLE
Issue remove request

### ISSUE THREAD

**Issue by orhanveli** [gboutte/nestjs-pdf#4]
Hey @gboutte, I created the issue #3 a couple of days ago, but it was from the company GitHub account. I realized it a little bit late, sorry for that. I wonder is there a chance to remove this issue or change the author?

Thanks in advance.

**Comment by gboutte** [comment]
Hi, no problem ! I could not find a way to change the author, but I deleted the issue.

**Comment by orhanveli** [comment]
I appreciated a lot 🙏🏻

best regards
